# Generated by Django 4.2 on 2023-04-25 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_id_todo_created_at_todo_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
        migrations.AlterModelTable(
            name='todo',
            table='todo',
        ),
    ]
